# Copyright 2022-2024, axodotdev
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# CI that:
#
# * checks for a Git Tag that looks like a release
# * builds artifacts with cargo-dist (archives, installers, hashes)
# * uploads those artifacts to temporary workflow stores
# * on success, uploads the artifacts to a GitHub Release
#
# Note that the GitHub Release will be created with a generated
# temporary title/body, you should edit it to be more readable.

name: Release

permissions:
  contents: write

# This task will run whenever you push a tag that looks like a version number
on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  # Run 'cargo dist plan' (or) 'cargo dist build'
  # This handles:
  # * checking if this is a version tag
  # * build archives and Linux installers
  # * generating and uploading hashes
  # * building installers
  plan:
    runs-on: "ubuntu-latest"
    outputs:
      val: ${{ steps.plan.outputs.manifest }}
      tag: ${{ steps.tag.outputs.tag }}
      tag-flag: ${{ steps.tag.outputs.tag-flag }}
      publishing: ${{ steps.plan.outputs.publishing }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Tag
        id: tag
        uses: actions/github-script@v7
        with:
          script: |
            // NOTE: we're copying the tag format in from release.yml, since
            // GITHUB_SHA isn't necessarily the commit being referred to.
            const semver = /^v(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?$/
            const tagName = context.ref.replace("refs/tags/", "")
            const match = semver.exec(tagName)
            let tag = tagName
            let tagFlag = "--tag=" + tag
            // If it's not a prerelease, make sure it's not a draft
            if (match && match[4] === undefined) {
              // "plan" will automatically use the latest draft release if one
              // already exists. We want to use a fresh one instead. To do that,
              // we generate a unique tag. We do this to avoid accidentally
              // adding to a "previous" release which wasn't "published" (in github's UI).
              //
              // The tradeoff here is that you will have to manually cleanup
              // old draft releases to avoid clutter.
              tag = `${match[1]}.${match[2]}.${match[3]}--draft${context.runNumber}`
              tagFlag = `--tag=${tag} --draft`
            }
            return { tag, tagFlag }

      - id: plan
        uses: axodotdev/cargo-dist-action@v0
        with:
          plan: true
          auto-hosts: false
          tag: ${{ fromJSON(steps.tag.outputs.result).tagFlag }}

  # Build and package all the platform-specific things
  build-artifacts:
    needs:
      - plan
    if: ${{ needs.plan.outputs.publishing == 'true' || github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        # For "which" values, use:
        # a) "plan" to get it from the plan
        # b) a triple to force that specific one (useful for debugging)
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: cargo-dist
        uses: axodotdev/cargo-dist-action@v0
        with:
          build-plan: ${{ needs.plan.outputs.val }}
          auto-hosts: false
          tag: ${{ needs.plan.outputs.tag }}
          install-updater: false

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            target/distrib/
          if-no-files-found: error

  # Create a GitHub Release while uploading all the artifacts
  release:
    needs:
      - plan
      - build-artifacts
    if: ${{ always() && needs.plan.outputs.publishing == 'true' }}
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch plan
        run: |
          # Download the plan from the previous task
          mkdir -p target/distrib/
          echo "$MANIFEST" > target/distrib/manifest.json
        env:
          MANIFEST: ${{ needs.plan.outputs.val }}

      - name: "Download all artifacts"
        uses: actions/download-artifact@v4
        with:
          path: target/distrib/
          merge-multiple: true

      - uses: axodotdev/cargo-dist-action@v0
        with:
          release: true
          tag: ${{ needs.plan.outputs.tag }}
          install-updater: false
