# Copyright 2022-2024, axodotdev
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# CI that:
#
# * checks for a Git Tag that looks like a release
# * builds artifacts with cargo-dist (archives, installers, hashes)
# * uploads those artifacts to temporary workflow stores
# * on success, uploads the artifacts to a GitHub Release

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  # Run 'cargo dist plan' (or) 'cargo dist build'
  plan:
    runs-on: "ubuntu-latest"
    outputs:
      val: ${{ steps.plan.outputs.manifest }}
      tag: ${{ steps.tag.outputs.tag }}
      tag-flag: ${{ steps.tag.outputs.tag-flag }}
      publishing: ${{ steps.plan.outputs.publishing }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Tag
        id: tag
        uses: actions/github-script@v7
        with:
          script: |
            const semver = /^v(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?$/
            const tagName = context.ref.replace("refs/tags/", "")
            const match = semver.exec(tagName)
            let tag = tagName
            let tagFlag = "--tag=" + tag
            if (match && match[4] === undefined) {
              tag = `${match[1]}.${match[2]}.${match[3]}--draft${context.runNumber}`
              tagFlag = `--tag=${tag} --draft`
            }
            return { tag, tagFlag }
      - id: plan
        uses: axodotdev/cargo-dist@v0
        with:
          plan: true
          auto-hosts: false
          tag: ${{ fromJSON(steps.tag.outputs.result).tagFlag }}

  build-artifacts:
    needs:
      - plan
    if: ${{ needs.plan.outputs.publishing == 'true' || github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: cargo-dist
        uses: axodotdev/cargo-dist@v0
        with:
          build-plan: ${{ needs.plan.outputs.val }}
          auto-hosts: false
          tag: ${{ needs.plan.outputs.tag }}
          install-updater: false
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            target/distrib/
          if-no-files-found: error

  release:
    needs:
      - plan
      - build-artifacts
    if: ${{ always() && needs.plan.outputs.publishing == 'true' }}
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Fetch plan
        run: |
          mkdir -p target/distrib/
          echo "$MANIFEST" > target/distrib/manifest.json
        env:
          MANIFEST: ${{ needs.plan.outputs.val }}
      - name: "Download all artifacts"
        uses: actions/download-artifact@v4
        with:
          path: target/distrib/
          merge-multiple: true
      - uses: axodotdev/cargo-dist@v0
        with:
          release: true
          tag: ${{ needs.plan.outputs.tag }}
          install-updater: false
